### PR TITLE
chore: adjust syntax to python type hints

### PR DESCRIPTION
**Pull request by deathaxe**
This PR provides required adjustments for pyright's syntax to work with https://github.com/sublimehq/Packages/pull/3736.

Unfortunately some of mensioned PRs changes break current syntax and I found no sane way around it.

### CODE REVIEW

**Comment by deathaxe** [comment]
https://github.com/sublimehq/Packages/pull/3736 has been merged and might be released with one of then next ST dev builds.

**Comment by jfcherng** [comment]
What will happen for stable build users if we merge and release this?

**Comment by deathaxe** [comment]
This being merged requires another `415x-` version prefix to be defined to restrict them to  those ST builds shipping new python syntax including PR 3736. The resulting changes to pyright's syntax are not forward or backward compatible. This PR won't work with ST4150 but without this PR pyright's syntax will fail with any upcomming ST415x build.

I haven't investigated impact of implementing https://github.com/sublimehq/Packages/issues/3793 so far.

**Comment by jfcherng** [comment]
In that case, I would like to vendor PR #3736 until there is a new stable release. Because we already ST 3 release and ST 4 release, I wouldn't like to create yet another one.

**Comment by deathaxe** [comment]
Sounds like a plan to make transition smoother.

**Comment by jfcherng** [comment]
Let's change
```yaml
extends: Packages/Python/Python.sublime-syntax
```
to 
```yaml
extends: Packages/LSP-pyright/syntaxes/Python.sublime-syntax
```

**Review by jfcherng — APPROVED** [review]

**Pull request merged**
