### PR TITLE
fix: "blender" dev_env not working

### PR DESCRIPTION
**Pull request by jfcherng**
fixes https://github.com/sublimelsp/LSP-pyright/issues/377

### CODE REVIEW

**Comment by Martysh12** [comment]
@jfcherng Running into another error:
```
[LSP-pyright][ERROR] Failed running command (('blender', '--background', '--python', 'C:\\Users\\Martin\\AppData\\Local\\Temp\\tmpynm3ed74\\sys_path_dumper.py')):   File "C:\Users\Martin\AppData\Local\Temp\tmpynm3ed74\sys_path_dumper.py", line 3
    with open("C:\Users\Martin\AppData\Local\Temp\tmpynm3ed74\sys_path.json", "w", encoding="utf-8") as f:
                                                                            ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[LSP-pyright][ERROR] Failed to update extra paths for dev environment "blender": [Errno 2] No such file or directory: 'C:\\Users\\Martin\\AppData\\Local\\Temp\\tmpynm3ed74\\sys_path.json'
```

**Comment by jfcherng** [comment]
Hi @Martysh12 , please try it again when you are available.

**Comment by Martysh12** [comment]
@jfcherng It works!
```
[LSP-pyright][DEBUG] Due to "dev_environment", new "analysis.extraPaths" is (operation = 'prepend'): ['E:\\SteamLibrary\\steamapps\\common\\Blender\\4.3\\scripts\\startup', 'E:\\SteamLibrary\\steamapps\\common\\Blender\\4.3\\scripts\\modules', 'E:\\SteamLibrary\\steamapps\\common\\Blender\\python311.zip', 'E:\\SteamLibrary\\steamapps\\common\\Blender\\4.3\\python\\DLLs', 'E:\\SteamLibrary\\steamapps\\common\\Blender\\4.3\\python\\Lib', 'E:\\SteamLibrary\\steamapps\\common\\Blender', 'E:\\SteamLibrary\\steamapps\\common\\Blender\\4.3\\python', 'E:\\SteamLibrary\\steamapps\\common\\Blender\\4.3\\python\\Lib\\site-packages', 'E:\\SteamLibrary\\steamapps\\common\\Blender\\4.3\\scripts\\freestyle\\modules', 'C:\\Users\\Martin\\AppData\\Roaming\\Blender Foundation\\Blender\\4.3\\scripts\\addons\\modules', 'E:\\SteamLibrary\\steamapps\\common\\Blender\\4.3\\scripts\\addons_core', 'C:\\Users\\Martin\\AppData\\Roaming\\Blender Foundation\\Blender\\4.3\\scripts\\addons', 'E:\\SteamLibrary\\steamapps\\common\\Blender\\4.3\\scripts\\startup\\bl_ui']
```

**Comment by jfcherng** [comment]
A new version has been released and should be available on Package Control within hours.

**Pull request merged**
